### ISSUE TITLE
fetch-h2 2.0 compatability

### ISSUE THREAD

**Issue by niklaskorz** [grantila/fetch-h2-br#2]
The package.json lists 1.x as peer dependency. Does this mean 2.0 is not supported?

**Comment by grantila** [comment]
No this is entirely my fault, it's compatible!

**Comment by niklaskorz** [comment]
Thanks for the quick reply. Also a lot of thanks for making fetch-h2, it's a joy to use, especially when being used to fetch from a browser environment.
